### ISSUE TITLE
fix 'contact' heading alignment in footer

### ISSUE THREAD

**Issue by meetjadhav999** [DiplomaTechCommunity/DTCWebsite#15]
Contact heading in footer of the website isn't aligned properly.

**Comment by meetjadhav999** [comment]
I'd like this issue to be assigned to me.

**Comment by CODEX108** [comment]
@meetjadhav999 can you please share a screenshot of the underlying issue?

**Comment by meetjadhav999** [comment]
![Screenshot (4)](https://github.com/DiplomaTechCommunity/DTCWebsite/assets/66296844/8a553418-1199-4676-91db-24ea0c711688)

This is happening because it is using 'contact-footer' class. If we just reuse the class 'footer-titel'( Someone has misspelled  title here, I'll fix that too) it will fix the alignment without writing any extra code.

**Comment by CODEX108** [comment]
@meetjadhav999 I've assigned the issue to you.

**Comment by CODEX108** [comment]
This issue has been resolved https://github.com/DiplomaTechCommunity/DTCWebsite/pull/16
